### ISSUE TITLE
The time it's not showed properly

### ISSUE THREAD

**Issue by victorhck** [victoriadrake/utc#1]
**Describe the bug**
the time it's not showed properly.
If I zoom the image, then works fine.

**To Reproduce**
1. Firefox in a 1366x768 laptop screen resolution

**Expected behavior**
See the time properly

**Screenshots**

![utc](https://user-images.githubusercontent.com/1514206/99957988-d6f33f80-2d88-11eb-9395-2f0189374b18.png)

**Desktop (please complete the following information):**
 - OS: openSUSE (GNU/Linux)
 - Browser: Firefox

**Comment by victoriadrake** [comment]
Thank you!
